name: my Second workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: List repo files
          run: ls -ltra

        - name: Execute shell script
          run: |
            chmod +x generate-ascii.sh
            ./generate-ascii.sh
