name: my Second workflow

on: push

jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: List repo files
          run: ls -ltra

        - name: whoami
          run: whoami

        - name: Execute shell script
          run: |
            chmod +x generate-ascii.sh
            ./generate-ascii.sh

        - name: Sleep for 20 seconds
          run: sleep 20

    test_job:
        needs: build_job
        runs-on: ubuntu-latest
        steps:
        - name: Test file exists
          run: grep -i "dragon" dragon.txt

    deploy_job:
        needs: [build_job, test_job]
        runs-on: ubuntu-latest
        steps:
        - name: Read file
          run: cat dragon.txt
    


